# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'

dpr_strategyqa:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: /home/joberant/home/urikatz1/dpr/datasets/strategyqa/embedded_corpus/corpus-enwiki-20200511.csv
  id_prefix: 'strategyqa:'
