# @package _group_

nq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-test

nq_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-train

nq_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-dev

trivia_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-test

trivia_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-train

trivia_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-dev

strategy_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /DPR/conf/datasets/StrategyQA dataset/strategyQA_train.json

strategy_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /DPR/conf/datasets/StrategyQA dataset/strategyQA_dev.json

strategy_gold_train:
  _target_: dpr.data.biencoder_data.JsonlQASrc
  file: /home/joberant/home/urikatz1/dpr/DPR/conf/datasets/StrategyQA dataset/modified_data/gold/strategyQA_train.json

strategy_gold_dev:
  _target_: dpr.data.biencoder_data.JsonlQASrc
  file: /home/joberant/home/urikatz1/dpr/DPR/conf/datasets/StrategyQA dataset/modified_data/gold/strategyQA_dev.json